FROM tensorflow/tensorflow:latest-gpu-jupyter

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update && apt-get -y install python3-pip

RUN pip3 install tensorflow-gpu jupyter
RUN pip3 install numpy matplotlib pandas pyyaml h5py
RUN pip3 install keras --no-deps

RUN ["mkdir", "notebook"]

COPY conf/.jupyter /root/.jupyter
COPY run_jupyter.sh /

EXPOSE 8888 6006

VOLUME /notebooks

CMD ["/run_jupyter.sh"]
